// GENERATED by generate-api-resource.mjs; DO NOT EDIT
import { createResourceClient } from "../../api/client";

export interface FilesResource {
  readonly id: string;
  readonly type: string;
  readonly attributes: Record<string, unknown>;
}

export interface FilesListQuery
  extends Record<string, string | number | undefined> {
  readonly cursor?: string;
  readonly pageSize?: number;
  readonly sort?: string;
}

export type CreateFilesRequest = Record<string, unknown>;
export type UpdateFilesRequest = Record<string, unknown>;

export const filesClient = createResourceClient<
  unknown,
  FilesListQuery,
  CreateFilesRequest,
  UpdateFilesRequest,
  FilesResource
>({
  path: "/api/files",
  supports: ["list", "create"],
});
