// GENERATED by generate-api-resource.mjs; DO NOT EDIT
import { createResourceClient } from "../../api/client";

export interface DocumentsResource {
  readonly id: string;
  readonly type: string;
  readonly attributes: Record<string, unknown>;
}

export interface DocumentsListQuery
  extends Record<string, string | number | undefined> {
  readonly cursor?: string;
  readonly pageSize?: number;
  readonly sort?: string;
}

export type CreateDocumentsRequest = Record<string, unknown>;
export type UpdateDocumentsRequest = Record<string, unknown>;

export const documentsClient = createResourceClient<
  unknown,
  DocumentsListQuery,
  CreateDocumentsRequest,
  UpdateDocumentsRequest,
  DocumentsResource
>({
  path: "/api/documents",
  supports: ["list", "create", "get"],
});
