// GENERATED by generate-api-resource.mjs; DO NOT EDIT
import { createResourceClient } from "../../api/client";

export interface PropertyEntriesResource {
  readonly id: string;
  readonly type: string;
  readonly attributes: Record<string, unknown>;
}

export interface PropertyEntriesListQuery
  extends Record<string, string | number | undefined> {
  readonly cursor?: string;
  readonly pageSize?: number;
  readonly sort?: string;
}

export type CreatePropertyEntriesRequest = Record<string, unknown>;
export type UpdatePropertyEntriesRequest = Record<string, unknown>;

export const propertyEntriesClient = createResourceClient<
  unknown,
  PropertyEntriesListQuery,
  CreatePropertyEntriesRequest,
  UpdatePropertyEntriesRequest,
  PropertyEntriesResource
>({
  path: "/api/property-entries",
  supports: ["list"],
});
