// GENERATED by generate-api-resource.mjs; DO NOT EDIT
import { createResourceClient } from "../../api/client";

export interface PropertyKeyPoliciesResource {
  readonly id: string;
  readonly type: string;
  readonly attributes: Record<string, unknown>;
}

export interface PropertyKeyPoliciesListQuery
  extends Record<string, string | number | undefined> {
  readonly cursor?: string;
  readonly pageSize?: number;
  readonly sort?: string;
}

export type CreatePropertyKeyPoliciesRequest = Record<string, unknown>;
export type UpdatePropertyKeyPoliciesRequest = Record<string, unknown>;

export const propertyKeyPoliciesClient = createResourceClient<
  unknown,
  PropertyKeyPoliciesListQuery,
  CreatePropertyKeyPoliciesRequest,
  UpdatePropertyKeyPoliciesRequest,
  PropertyKeyPoliciesResource
>({
  path: "/api/property-key-policies",
  supports: ["list"],
});
