// GENERATED by generate-api-resource.mjs; DO NOT EDIT
import { createResourceClient } from "../../api/client";

export interface SearchSessionsResource {
  readonly id: string;
  readonly type: string;
  readonly attributes: Record<string, unknown>;
}

export interface SearchSessionsListQuery
  extends Record<string, string | number | undefined> {
  readonly cursor?: string;
  readonly pageSize?: number;
  readonly sort?: string;
}

export type CreateSearchSessionsRequest = Record<string, unknown>;
export type UpdateSearchSessionsRequest = Record<string, unknown>;

export const searchSessionsClient = createResourceClient<
  unknown,
  SearchSessionsListQuery,
  CreateSearchSessionsRequest,
  UpdateSearchSessionsRequest,
  SearchSessionsResource
>({
  path: "/api/search-sessions",
  supports: ["get"],
});
