// GENERATED by generate-api-resource.mjs; DO NOT EDIT
import { createVertexRoute } from "../../lib/api/route";
import { documentsCollectionRouteSpec } from "../../lib/resources/exports-documents/documents.hooks";
import withSession from "../../lib/with-session";

export const handleDocuments = createVertexRoute(documentsCollectionRouteSpec);
export default withSession(handleDocuments);
