// GENERATED by generate-api-resource.mjs; DO NOT EDIT
import { createVertexRoute } from "../../lib/api/route";
import { filesCollectionRouteSpec } from "../../lib/resources/core-import-library/files.hooks";
import withSession from "../../lib/with-session";

export const handleFiles = createVertexRoute(
  filesCollectionRouteSpec
);
export default withSession(handleFiles);
