// GENERATED by generate-api-resource.mjs; DO NOT EDIT
import { createVertexRoute } from "../../lib/api/route";
import { propertyEntriesCollectionRouteSpec } from "../../lib/resources/properties-search/property-entries.hooks";
import withSession from "../../lib/with-session";

export const handlePropertyEntries = createVertexRoute(
  propertyEntriesCollectionRouteSpec
);
export default withSession(handlePropertyEntries);
