// GENERATED by generate-api-resource.mjs; DO NOT EDIT
import { createVertexRoute } from "../../lib/api/route";
import { propertyKeyPoliciesCollectionRouteSpec } from "../../lib/resources/properties-search/property-key-policies.hooks";
import withSession from "../../lib/with-session";

export const handlePropertyKeyPolicies = createVertexRoute(
  propertyKeyPoliciesCollectionRouteSpec
);
export default withSession(handlePropertyKeyPolicies);
