// GENERATED by generate-api-resource.mjs; DO NOT EDIT
import { createVertexRoute } from "../../lib/api/route";
import { sceneWorkspaceViewsCollectionRouteSpec } from "../../lib/resources/scene-workspace/scene-workspace-views.hooks";
import withSession from "../../lib/with-session";

export const handleSceneWorkspaceViews = createVertexRoute(sceneWorkspaceViewsCollectionRouteSpec);
export default withSession(handleSceneWorkspaceViews);
