// GENERATED by generate-api-resource.mjs; DO NOT EDIT
import { createVertexRoute } from "../../lib/api/route";
import { sceneWorkspaceItemsCollectionRouteSpec } from "../../lib/resources/scene-workspace/scene-workspace-items.hooks";
import withSession from "../../lib/with-session";

export const handleSceneWorkspaceItems = createVertexRoute(sceneWorkspaceItemsCollectionRouteSpec);
export default withSession(handleSceneWorkspaceItems);
