// GENERATED by generate-api-resource.mjs; DO NOT EDIT
import { createVertexRoute } from "../../../lib/api/route";
import { searchSessionsDetailRouteSpec } from "../../../lib/resources/properties-search/search-sessions.hooks";
import withSession from "../../../lib/with-session";

export const handleSearchSessionsDetail = createVertexRoute(
  searchSessionsDetailRouteSpec
);
export default withSession(handleSearchSessionsDetail);
