// GENERATED by generate-api-resource.mjs; DO NOT EDIT
import { createVertexRoute } from "../../../lib/api/route";
import { documentsDetailRouteSpec } from "../../../lib/resources/exports-documents/documents.hooks";
import withSession from "../../../lib/with-session";

export const handleDocumentsDetail = createVertexRoute(
  documentsDetailRouteSpec
);
export default withSession(handleDocumentsDetail);
