name: build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 22.x }
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test:ci
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ github.sha }}
          path: ./coverage
          retention-days: 10
      - name: Build
        run: yarn build

  sonar-analysis:
    runs-on: ubuntu-latest
    needs:
      - build
    env:
      ACTIONS_SONAR_TOKEN: ${{ secrets.ACTIONS_SONAR_TOKEN }}
    steps:
      - name: SonarQube Analysis
        uses: Vertexvis/actions/sonar-analysis@main
        with:
          service-name: ${{ github.event.repository.name }}
          sonar-coverage-property: "sonar.javascript.lcov.reportPaths"
          coverage-report-path: "./coverage/lcov.info"
          sources: "./src"
          tests: "./src"
          sbt-dependencies-artifact: ""
