// GENERATED by generate-api-resource.mjs; DO NOT EDIT
import { createResourceClient } from "../../api/client";

export interface SceneWorkspaceViewsResource {
  readonly id: string;
  readonly type: string;
  readonly attributes: Record<string, unknown>;
}

export interface SceneWorkspaceViewsListQuery
  extends Record<string, string | number | undefined> {
  readonly cursor?: string;
  readonly pageSize?: number;
  readonly sort?: string;
}

export type CreateSceneWorkspaceViewsRequest = Record<string, unknown>;
export type UpdateSceneWorkspaceViewsRequest = Record<string, unknown>;

export const sceneWorkspaceViewsClient = createResourceClient<
  unknown,
  SceneWorkspaceViewsListQuery,
  CreateSceneWorkspaceViewsRequest,
  UpdateSceneWorkspaceViewsRequest,
  SceneWorkspaceViewsResource
>({
  path: "/api/scene-workspace-views",
  supports: ["list"],
});
