// GENERATED by generate-api-resource.mjs; DO NOT EDIT
import { createResourceClient } from "../../api/client";

export interface SceneWorkspaceItemsResource {
  readonly id: string;
  readonly type: string;
  readonly attributes: Record<string, unknown>;
}

export interface SceneWorkspaceItemsListQuery
  extends Record<string, string | number | undefined> {
  readonly cursor?: string;
  readonly pageSize?: number;
  readonly sort?: string;
}

export type CreateSceneWorkspaceItemsRequest = Record<string, unknown>;
export type UpdateSceneWorkspaceItemsRequest = Record<string, unknown>;

export const sceneWorkspaceItemsClient = createResourceClient<
  unknown,
  SceneWorkspaceItemsListQuery,
  CreateSceneWorkspaceItemsRequest,
  UpdateSceneWorkspaceItemsRequest,
  SceneWorkspaceItemsResource
>({
  path: "/api/scene-workspace-items",
  supports: ["list"],
});
